# IMPORTANT:
# This file contains the default configuration values of the server.
# Modifications to this file should be handled with care. They maybe
# lost the next time the application is updated and create a security
# risk by exposing the shared secret.

# RECOMMENDATION:
# All configuration values/overrides should be done via the environment as
# opposed to modifying the configs. This particularly applies to the required
# keys which must be set before the application has started

# EXAMPLE:
# To set the shared secret in the environment:
# export jwt_shared_secret=...Your shared secret ...
# export ... All the other REQUIRED configs ...

# REQUIRED:
# jwt_shared_secret:  # [REQUIRED - Export for enhanced security]

# ENABLE UPSTREAM MODE:
# Export the following configs to put the server into upstream mode.
# Particular care should be taken not to hard set the `remote_jwt` in this
# config for security reasons.
remote_cluster: default
# remote_jwt:
# remote_url: http://localhost:6301

# DYNAMIC DEFAULTS:
# The following may use relative paths from the install directory
# or hard coded to be an absolute path
templates_dir: var/templates

# STATIC DEFAULTS:
log_level: info

development:
  remote_url: http://localhost:6301
  log_level:  debug

test:
  remote_url: http://localhost:6301
  log_level: error
  remote_cluster: demo-cluster
  remote_jwt: ''
